
departments = { 'Accounting':           'Business',
                'African':              'Culture',
                'Culture':              'CoSS',
                'Anthropology':         'Culture',
                'Arts':                 'CAL',
                'Astronomy':            'Physics',
                'Physics':              'EPS',
                'Biology':              'LES',
                'Business':             '',
                'Law':                  'CAL',
                'Chemical Engineering': 'EPS',
                'Engineering':          'EPS',
                'Chemistry':            'EPS',
                'Civil Engineering':    'Engineering',
                'Classics':             'History',
                'History':              'CoSS',
                'CAL':                  '',
                'EPS':                  '',
                'CoSS':                 '',
                'MDS':                  '',
                'LES':                  '',
                'Archaeology':          'History',
                'Computer Science':     'EPS',
                'Dentistry':            'MDS',
                'Management':           'Business',
                'Social':               'CoSS',
                'Development':          'Social',
                'Disability':           'Social',
                'Drama':                'Arts',
                'Geography':            'Environment',
                'Environment':          'LES',
                'European':             'Language',
                'Language':             'Arts',
                'Ecology':              'Environment',
                'Economics':            'Business',
                'Education':            'Social',
                'Electronics':          'Engineering',
                'English':              'Language',
                'Literature':           'Language',
                'Film':                 'Arts',
                'Writing':              'English',
                'Finance':              'Business',
                'Global':               'Environmental',
                'Government':           'Law',
                'Health':               'MDS',
                'Marketing':            'Business',
                'Mathematics':          'EPS',
                'Mechanics':            'Engineering',
                'Medieval':             'History',
                'Materials':            'EPS',
                'Music':                'Arts',
                'Philosophy':           'Social',
                'Theology':             'Social',
                'Religion':             'Religion',
                'Physiotherapy':        'LES',
                'Political':            'Social',
                'Psychology':           'Social',
                'Sociology':            'Social',
                'Criminology':          'Social',
                'Sport':                'LES'}

